name: cequalw2
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.9
  - pandas>=1.5.0
  - numpy>=1.21.0
  - matplotlib>=3.5.0
  - seaborn>=0.11.0
  - holoviews>=1.15.0
  - panel>=1.0.0
  - bokeh>=3.0.0
  - h5py>=3.7.0
  - sqlalchemy>=2.0.0
  - pyyaml>=6.0
  - pyqt>=5.15.0
  - jupyter>=1.0.0
  - ipywidgets>=8.0.0
  - jupyterlab>=4.0.0
  - pytest>=7.0.0
  - pytest-cov>=4.0.0
  - black>=23.0.0
  - isort>=5.12.0
  - flake8>=6.0.0
  - mypy>=1.0.0
  - pre-commit>=3.0.0
  - sphinx>=5.0.0
  - sphinx-rtd-theme>=1.2.0
  - myst-parser>=1.0.0
  - pip
  - pip:
      - -e .